import { executeCommand, commandExists } from '../shell-executor'
import type { NetworkInterface, DNSConfig, ProxyHost } from '@/types'
import { readFile, writeFile } from 'fs/promises'
import { existsSync } from 'fs'

/**
 * Lists all network interfaces
 */
export async function listInterfaces(): Promise<NetworkInterface[]> {
  const result = await executeCommand('ip', ['-j', 'addr', 'show'])
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'Failed to list interfaces')
  }
  
  try {
    const data = JSON.parse(result.stdout)
    const interfaces: NetworkInterface[] = []
    
    for (const iface of data) {
      const addresses = (iface.addr_info || []).map((addr: { local: string; prefixlen: number; family: string }) => ({
        address: addr.local,
        netmask: prefixToNetmask(addr.prefixlen, addr.family),
        family: addr.family === 'inet' ? 'inet' : 'inet6' as const,
      }))
      
      // Get interface stats
      const statsResult = await executeCommand('cat', [`/sys/class/net/${iface.ifname}/statistics/rx_bytes`])
      const rxBytes = parseInt(statsResult.stdout) || 0
      const txResult = await executeCommand('cat', [`/sys/class/net/${iface.ifname}/statistics/tx_bytes`])
      const txBytes = parseInt(txResult.stdout) || 0
      
      interfaces.push({
        name: iface.ifname,
        type: getInterfaceType(iface.ifname, iface.link_type),
        mac: iface.address || '',
        state: iface.operstate === 'UP' ? 'up' : 'down',
        mtu: iface.mtu || 1500,
        addresses,
        dhcp: false, // Would need to check netplan config
        stats: {
          rx: rxBytes,
          tx: txBytes,
          rxPackets: 0,
          txPackets: 0,
        },
      })
    }
    
    return interfaces
  } catch {
    return []
  }
}

/**
 * Gets a specific interface
 */
export async function getInterface(name: string): Promise<NetworkInterface | null> {
  const interfaces = await listInterfaces()
  return interfaces.find(i => i.name === name) || null
}

/**
 * Sets interface up or down
 */
export async function setInterfaceState(name: string, state: 'up' | 'down'): Promise<void> {
  const result = await executeCommand('ip', ['link', 'set', name, state], { sudo: true })
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || `Failed to set interface ${state}`)
  }
}

/**
 * Configures interface with static IP
 */
export async function configureStaticIP(
  interfaceName: string,
  address: string,
  netmask: string,
  gateway?: string,
  dns?: string[]
): Promise<void> {
  // Generate netplan config
  const prefix = netmaskToPrefix(netmask)
  const config = {
    network: {
      version: 2,
      ethernets: {
        [interfaceName]: {
          addresses: [`${address}/${prefix}`],
          ...(gateway && { gateway4: gateway }),
          ...(dns && { nameservers: { addresses: dns } }),
        },
      },
    },
  }
  
  // Write to netplan
  const configPath = `/etc/netplan/99-homelab-${interfaceName}.yaml`
  await writeFile(configPath, `# Generated by HomeLab Manager\n${JSON.stringify(config, null, 2).replace(/"([^"]+)":/g, '$1:')}`)
  
  // Apply netplan
  const result = await executeCommand('netplan', ['apply'], { sudo: true })
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'Failed to apply network configuration')
  }
}

/**
 * Configures interface for DHCP
 */
export async function configureDHCP(interfaceName: string): Promise<void> {
  const config = {
    network: {
      version: 2,
      ethernets: {
        [interfaceName]: {
          dhcp4: true,
        },
      },
    },
  }
  
  const configPath = `/etc/netplan/99-homelab-${interfaceName}.yaml`
  await writeFile(configPath, `# Generated by HomeLab Manager\n${JSON.stringify(config, null, 2).replace(/"([^"]+)":/g, '$1:')}`)
  
  const result = await executeCommand('netplan', ['apply'], { sudo: true })
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'Failed to apply network configuration')
  }
}

/**
 * Gets DNS configuration
 */
export async function getDNSConfig(): Promise<DNSConfig> {
  // Try systemd-resolved first
  const resolvedResult = await executeCommand('resolvectl', ['status'])
  if (resolvedResult.exitCode === 0) {
    const nameservers: string[] = []
    const searchDomains: string[] = []
    
    const dnsMatches = resolvedResult.stdout.matchAll(/DNS Servers:\s*(.+)/g)
    for (const match of dnsMatches) {
      nameservers.push(...match[1].trim().split(/\s+/))
    }
    
    const searchMatches = resolvedResult.stdout.matchAll(/DNS Domain:\s*(.+)/g)
    for (const match of searchMatches) {
      searchDomains.push(...match[1].trim().split(/\s+/))
    }
    
    return {
      nameservers: [...new Set(nameservers)],
      searchDomains: [...new Set(searchDomains)],
      resolvConfPath: '/etc/resolv.conf',
    }
  }
  
  // Fallback to resolv.conf
  try {
    const content = await readFile('/etc/resolv.conf', 'utf-8')
    const nameservers = content.match(/nameserver\s+(\S+)/g)?.map(s => s.replace('nameserver ', '')) || []
    const searchDomains = content.match(/search\s+(.+)/)?.[1]?.split(/\s+/) || []
    
    return {
      nameservers,
      searchDomains,
      resolvConfPath: '/etc/resolv.conf',
    }
  } catch {
    return {
      nameservers: [],
      searchDomains: [],
      resolvConfPath: '/etc/resolv.conf',
    }
  }
}

/**
 * Sets DNS servers
 */
export async function setDNSServers(nameservers: string[], searchDomains?: string[]): Promise<void> {
  // Check if using systemd-resolved
  const hasResolved = await commandExists('resolvectl')
  
  if (hasResolved) {
    // Use resolvectl
    for (const ns of nameservers) {
      await executeCommand('resolvectl', ['dns', 'eth0', ns], { sudo: true })
    }
    if (searchDomains?.length) {
      await executeCommand('resolvectl', ['domain', 'eth0', ...searchDomains], { sudo: true })
    }
  } else {
    // Write to resolv.conf directly
    let content = '# Generated by HomeLab Manager\n'
    for (const ns of nameservers) {
      content += `nameserver ${ns}\n`
    }
    if (searchDomains?.length) {
      content += `search ${searchDomains.join(' ')}\n`
    }
    
    await writeFile('/etc/resolv.conf', content)
  }
}

/**
 * Creates a network bridge
 */
export async function createBridge(name: string, interfaces: string[]): Promise<void> {
  // Create bridge
  let result = await executeCommand('ip', ['link', 'add', name, 'type', 'bridge'], { sudo: true })
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'Failed to create bridge')
  }
  
  // Add interfaces to bridge
  for (const iface of interfaces) {
    result = await executeCommand('ip', ['link', 'set', iface, 'master', name], { sudo: true })
    if (result.exitCode !== 0) {
      throw new Error(result.stderr || `Failed to add ${iface} to bridge`)
    }
  }
  
  // Bring bridge up
  result = await executeCommand('ip', ['link', 'set', name, 'up'], { sudo: true })
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'Failed to bring bridge up')
  }
}

/**
 * Deletes a network bridge
 */
export async function deleteBridge(name: string): Promise<void> {
  // Bring bridge down
  await executeCommand('ip', ['link', 'set', name, 'down'], { sudo: true })
  
  // Delete bridge
  const result = await executeCommand('ip', ['link', 'delete', name, 'type', 'bridge'], { sudo: true })
  if (result.exitCode !== 0) {
    throw new Error(result.stderr || 'Failed to delete bridge')
  }
}

// ==================== Reverse Proxy (Nginx) Functions ====================

const NGINX_PROXY_DIR = '/etc/nginx/sites-available'
const NGINX_ENABLED_DIR = '/etc/nginx/sites-enabled'

/**
 * Lists reverse proxy hosts
 */
export async function listProxyHosts(): Promise<ProxyHost[]> {
  const result = await executeCommand('ls', [NGINX_PROXY_DIR])
  if (result.exitCode !== 0) {
    return []
  }
  
  const hosts: ProxyHost[] = []
  const files = result.stdout.split('\n').filter(f => f.endsWith('.conf'))
  
  for (const file of files) {
    try {
      const content = await readFile(`${NGINX_PROXY_DIR}/${file}`, 'utf-8')
      const host = parseNginxProxyConfig(file, content)
      if (host) {
        // Check if enabled
        host.enabled = existsSync(`${NGINX_ENABLED_DIR}/${file}`)
        hosts.push(host)
      }
    } catch {
      // Skip unparseable files
    }
  }
  
  return hosts
}

/**
 * Creates a reverse proxy host
 */
export async function createProxyHost(host: Omit<ProxyHost, 'id'>): Promise<ProxyHost> {
  const id = host.domain.replace(/\./g, '-')
  const filename = `${id}.conf`
  const config = generateNginxProxyConfig({ ...host, id })
  
  // Write config
  await writeFile(`${NGINX_PROXY_DIR}/${filename}`, config)
  
  // Enable if requested
  if (host.enabled) {
    await executeCommand('ln', ['-sf', `${NGINX_PROXY_DIR}/${filename}`, `${NGINX_ENABLED_DIR}/${filename}`], { sudo: true })
  }
  
  // Test and reload nginx
  const testResult = await executeCommand('nginx', ['-t'], { sudo: true })
  if (testResult.exitCode !== 0) {
    // Remove invalid config
    await executeCommand('rm', [`${NGINX_PROXY_DIR}/${filename}`], { sudo: true })
    throw new Error(testResult.stderr || 'Invalid nginx configuration')
  }
  
  await executeCommand('systemctl', ['reload', 'nginx'], { sudo: true })
  
  return { ...host, id }
}

/**
 * Updates a reverse proxy host
 */
export async function updateProxyHost(id: string, host: Partial<ProxyHost>): Promise<void> {
  const filename = `${id}.conf`
  
  // Read existing config
  const existingHosts = await listProxyHosts()
  const existing = existingHosts.find(h => h.id === id)
  if (!existing) {
    throw new Error('Proxy host not found')
  }
  
  // Generate new config
  const updated = { ...existing, ...host }
  const config = generateNginxProxyConfig(updated)
  
  // Write config
  await writeFile(`${NGINX_PROXY_DIR}/${filename}`, config)
  
  // Update enabled state
  if (host.enabled !== undefined) {
    if (host.enabled) {
      await executeCommand('ln', ['-sf', `${NGINX_PROXY_DIR}/${filename}`, `${NGINX_ENABLED_DIR}/${filename}`], { sudo: true })
    } else {
      await executeCommand('rm', ['-f', `${NGINX_ENABLED_DIR}/${filename}`], { sudo: true })
    }
  }
  
  // Test and reload nginx
  const testResult = await executeCommand('nginx', ['-t'], { sudo: true })
  if (testResult.exitCode !== 0) {
    throw new Error(testResult.stderr || 'Invalid nginx configuration')
  }
  
  await executeCommand('systemctl', ['reload', 'nginx'], { sudo: true })
}

/**
 * Deletes a reverse proxy host
 */
export async function deleteProxyHost(id: string): Promise<void> {
  const filename = `${id}.conf`
  
  // Remove from enabled
  await executeCommand('rm', ['-f', `${NGINX_ENABLED_DIR}/${filename}`], { sudo: true })
  
  // Remove config
  await executeCommand('rm', ['-f', `${NGINX_PROXY_DIR}/${filename}`], { sudo: true })
  
  // Reload nginx
  await executeCommand('systemctl', ['reload', 'nginx'], { sudo: true })
}

// Helper functions
function getInterfaceType(name: string, linkType?: string): NetworkInterface['type'] {
  if (name === 'lo') return 'loopback'
  if (name.startsWith('br') || name.startsWith('virbr')) return 'bridge'
  if (name.startsWith('vlan') || name.includes('.')) return 'vlan'
  if (name.startsWith('bond')) return 'bond'
  if (name.startsWith('veth') || name.startsWith('tap') || name.startsWith('tun')) return 'virtual'
  if (linkType === 'ether') return 'ethernet'
  return 'ethernet'
}

function prefixToNetmask(prefix: number, family: string): string {
  if (family === 'inet6') {
    return `/${prefix}`
  }
  const mask = ~(2 ** (32 - prefix) - 1)
  return [
    (mask >>> 24) & 255,
    (mask >>> 16) & 255,
    (mask >>> 8) & 255,
    mask & 255,
  ].join('.')
}

function netmaskToPrefix(netmask: string): number {
  const parts = netmask.split('.').map(Number)
  let prefix = 0
  for (const part of parts) {
    prefix += (part >>> 0).toString(2).split('1').length - 1
  }
  return prefix
}

function parseNginxProxyConfig(filename: string, content: string): ProxyHost | null {
  const serverNameMatch = content.match(/server_name\s+([^;]+);/)
  const proxyPassMatch = content.match(/proxy_pass\s+https?:\/\/([^:;/]+):?(\d+)?/)
  const sslMatch = content.match(/listen\s+443\s+ssl/)
  
  if (!serverNameMatch) return null
  
  return {
    id: filename.replace('.conf', ''),
    domain: serverNameMatch[1].trim(),
    target: proxyPassMatch?.[1] || 'localhost',
    port: parseInt(proxyPassMatch?.[2] || '80'),
    ssl: !!sslMatch,
    forceSSL: content.includes('return 301 https://'),
    enabled: false,
    cacheEnabled: content.includes('proxy_cache'),
    websocketSupport: content.includes('Upgrade'),
  }
}

function generateNginxProxyConfig(host: ProxyHost): string {
  const upstream = `${host.target}:${host.port}`
  
  let config = `# Generated by HomeLab Manager
server {
    listen 80;
    server_name ${host.domain};
`

  if (host.forceSSL && host.ssl) {
    config += `
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${host.domain};

    ssl_certificate ${host.sslCertPath || `/etc/letsencrypt/live/${host.domain}/fullchain.pem`};
    ssl_certificate_key ${host.sslKeyPath || `/etc/letsencrypt/live/${host.domain}/privkey.pem`};
`
  }

  config += `
    location / {
        proxy_pass http://${upstream};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
`

  if (host.websocketSupport) {
    config += `
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
`
  }

  config += `    }
}
`

  return config
}
